In [49]:
import numpy as np
import pandas as pd

In [112]:
df = pd.read_csv("train.csv")

def clean_data(df):
    del df['Ticket']
    del df['Name']
    del df['SibSp']
    del df['Parch']
    del df['Cabin']
    del df['Embarked']
    del df['Fare']

    df['Sex'] = df['Sex'].replace('male', 0).replace('female', 1)
    df = df.rename(columns = {'Sex': 'IsFemale'})

clean_data(df)
df.iloc[0:20]

    Survived  Pclass  Sex   Age
0          0       3    0  22.0
1          1       1    1  38.0
2          1       3    1  26.0
3          1       1    1  35.0
4          0       3    0  35.0
5          0       3    0   NaN
6          0       1    0  54.0
7          0       3    0   2.0
8          1       3    1  27.0
9          1       2    1  14.0
10         1       3    1   4.0
11         1       1    1  58.0
12         0       3    0  20.0
13         0       3    0  39.0
14         0       3    1  14.0
15         1       2    1  55.0
16         0       3    0   2.0
17         1       2    0   NaN
18         0       3    1  31.0
19         1       3    1   NaN

In [82]:
# Linear regression to fill in missing ages
from sklearn import linear_model

non_age_columns = ['Pclass', 'IsFemale']

complete_dataset = df[df['Age'] > 0]
X = complete_dataset[non_age_columns]
Y = complete_dataset[['Age']]
age_regressor = linear_model.LinearRegression()
age_regressor.fit(X, Y)

for index, row in df.iterrows():
    if np.isnan(row['Age']):
        estimated_age = age_regressor.predict(row[non_age_columns].reshape(1, -1))[0][0]
        df.ix[index, 'Age'] = estimated_age
        
df.iloc[0:20]

    Survived  Pclass  IsFemale        Age
0          0       3         0  22.000000
1          1       1         1  38.000000
2          1       3         1  26.000000
3          1       1         1  35.000000
4          0       3         0  35.000000
5          0       3         0  26.801905
6          0       1         0  54.000000
7          0       3         0   2.000000
8          1       3         1  27.000000
9          1       2         1  14.000000
10         1       3         1   4.000000
11         1       1         1  58.000000
12         0       3         0  20.000000
13         0       3         0  39.000000
14         0       3         1  14.000000
15         1       2         1  55.000000
16         0       3         0   2.000000
17         1       2         0  28.328407
18         0       3         1  31.000000
19         1       3         1  19.008593

In [103]:
# Train a neural network to estimate survival

from sklearn.neural_network import MLPClassifier

non_survival_columns = ['Pclass', 'IsFemale', 'Age']

X = df[non_survival_columns]
y = df.as_matrix(['Survived']).T[0]

survival_classifier = MLPClassifier(solver='lbfgs', alpha=0.001, hidden_layer_sizes=(10, 10), random_state=1)
survival_classifier.fit(X, y)
print(survival_classifier.score(X, y))

0.830527497194

In [116]:
# Make estimations

test_data = pd.read_csv("test.csv")
test_data['Survived'] = 0 # Default estimation
clean_data(test_data)
test_data = test_data.rename(columns = {'Sex': 'IsFemale'})

for index, row in test_data.iterrows():
    print(index)
    print(row[non_survival_columns])
    if (np.isnan(row[''])):
        test_data.ix[index, 'Age']
    test_data.ix[index, 'Survived'] = survival_classifier.predict(row[non_survival_columns])
    
1

0
Pclass       3.0
IsFemale     NaN
Age         34.5
Name: 0, dtype: float64

/Users/andy/Applications/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').